networks:
  default:

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - default
    ports:
      - "3306:3306"

  doli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doli
    environment:
      - DOLI_DB_HOST
      - DOLI_DB_HOST_PORT
      - DOLI_DB_NAME
      - DOLI_DB_USER
      - DOLI_DB_PASSWORD
      - DOLI_URL_ROOT
      - DOLI_ADMIN_LOGIN
      - DOLI_ADMIN_PASSWORD
      - DOLI_INSTALL_AUTO
      - DOLI_PROD
      - DOLI_INIT_DEMO
      - DOLI_CRON
      - DOLI_COMPANY_NAME
      - WWW_USER_ID
      - WWW_GROUP_ID
    networks:
      - default
    ports:
      - "80:80"
    depends_on:
      - mariadb
    volumes:
      - ./documents:/var/www/documents
      - ./htdocs:/var/www/html/
