services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dolidb}
      MYSQL_USER: ${MYSQL_USER:-dolidbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dolidbpass}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: dolibarr/dolibarr:19.0.4-php8.2
    container_name: doli
    environment:
      DOLI_DB_HOST: ${DOLI_DB_HOST:-mariadb}
      DOLI_DB_NAME: ${DOLI_DB_NAME:-dolidb}
      DOLI_DB_USER: ${DOLI_DB_USER:-dolidbuser}
      DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD:-dolidbpass}
      DOLI_URL_ROOT: "${DOLI_URL_ROOT:-http://localhost}"
      DOLI_ADMIN_LOGIN: "${DOLI_ADMIN_LOGIN:-admin}"
      DOLI_ADMIN_PASSWORD: "${DOLI_ADMIN_PASSWORD:-admin}"
      DOLI_INSTALL_AUTO: ${DOLI_INSTALL_AUTO:-1}
      DOLI_PROD: ${DOLI_PROD:-1}
      DOLI_INIT_DEMO: ${DOLI_INIT_DEMO:-0}
      DOLI_CRON: ${DOLI_CRON:-0}
      DOLI_COMPANY_NAME: ${DOLI_COMPANY_NAME:-MyBigCompany}
    ports:
      - "80:80"
    depends_on:
      - mariadb
    volumes:
      - ./documents:/var/www/documents
      - ./htdocs:/var/www/html/
      - ./htdocs/custom:/var/www/html/custom
    extra_hosts:
      - host.docker.internal:host-gateway
